const { env } = process;
var provinceMap = {
  '北京市': 1,
  '天津市': 2,
  '河北省': 3,
  '山西省': 4,
  '内蒙古自治区': 5,
  '辽宁省': 6,
  '吉林省': 7,
  '黑龙江省': 8,
  '上海市': 9,
  '江苏省': 10,
  '浙江省': 11,
  '安徽省': 12,
  '福建省': 13,
  '江西省': 14,
  '山东省': 15,
  '河南省': 16,
  '湖北省': 17,
  '湖南省': 18,
  '广东省': 19,
  '广西壮族自治区': 20,
  '海南省': 21,
  '重庆市': 22,
  '四川省': 23,
  '贵州省': 24,
  '云南省': 25,
  '西藏自治区': 26,
  '陕西省': 27,
  '甘肃省': 28,
  '青海省': 29,
  '宁夏回族自治区': 30,
  '新疆维吾尔自治区': 31,
  '香港': 32,
  '澳门': 33,
  '台湾': 34
}
const config = {
  HOST: env.HOST,
  PORT: env.PORT,
  MINI_APPID: env.MINI_APPID,
  MINI_SECRET:env.MINI_SECRET,
  TENCENT_MAP_KEY: env.TENCENT_MAP_KEY,
  PROVINCEMAP:provinceMap,
  RDS_PORT: env.RDS_PORT,
  RDS_HOST: env.RDS_HOST,
  RDS_PWD: env.RDS_PWD,
  JWTSECRET: env.JWTSECRET
}

module.exports = config